title: Daniel Hernández García
description: Postdoctoral Research Associate in HRI at University of Manchester.
show_downloads: false
google_analytics:
email_address: daniel.hernandezgarcia@manchester.ac.uk


github_username: dhgarcia
twitter_username: d_hgarcia
linkedin_username: dhgarcia
researchgate_username: Daniel_Hernandez_Garcia
facebook_username: daniel.j.hernandez.garcia


show_excerpts: true
theme: jekyll-theme-dinky

plugins:
  - jemoji
  - jekyll-email-protect
