title: Daniel Hernández García
description: Research Fellow in Human-Robot Interaction at University of Plymouth.
show_downloads: false
google_analytics:
twitter_username: d_hgarcia
theme: jekyll-theme-dinky
